src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $preparationTime = null;

    #[ORM\Column(length: 255)]
    private ?string $break = null;

    #[ORM\Column(length: 255)]
    private ?string $cooking_time = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $ingredients = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $steps = null;

    #[ORM\ManyToMany(targetEntity: Allergens::class, mappedBy: 'recipe')]
    private Collection $allergens;

    #[ORM\ManyToMany(targetEntity: DietTypes::class, mappedBy: 'recipe')]
    private Collection $dietTypes;

    #[ORM\Column(length: 255)]
    private ?string $imgFilename = null;

    #[ORM\Column]
    private ?bool $free = null;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->allergens = new ArrayCollection();
        $this->dietTypes = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPreparationTime(): ?string
    {
        return $this->preparationTime;
    }

    public function setPreparationTime(string $preparationTime): static
    {
        $this->preparationTime = $preparationTime;

        return $this;
    }

    public function getBreak(): ?string
    {
        return $this->break;
    }

    public function setBreak(string $break): static
    {
        $this->break = $break;

        return $this;
    }

    public function getCookingTime(): ?string
    {
        return $this->cooking_time;
    }

    public function setCookingTime(string $cooking_time): static
    {
        $this->cooking_time = $cooking_time;

        return $this;
    }

    public function getIngredients(): ?string
    {
        return $this->ingredients;
    }

    public function setIngredients(string $ingredients): static
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getSteps(): ?string
    {
        return $this->steps;
    }

    public function setSteps(string $steps): static
    {
        $this->steps = $steps;

        return $this;
    }

    /**
     * @return Collection<int, Allergens>
     */
    public function getAllergens(): Collection
    {
        return $this->allergens;
    }

    public function addAllergen(Allergens $allergen): static
    {
        if (!$this->allergens->contains($allergen)) {
            $this->allergens->add($allergen);
            $allergen->addRecipe($this);
        }

        return $this;
    }

    public function removeAllergen(Allergens $allergen): static
    {
        if ($this->allergens->removeElement($allergen)) {
            $allergen->removeRecipe($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, DietTypes>
     */
    public function getDietTypes(): Collection
    {
        return $this->dietTypes;
    }

    public function addDietType(DietTypes $dietType): static
    {
        if (!$this->dietTypes->contains($dietType)) {
            $this->dietTypes->add($dietType);
            $dietType->addRecipe($this);
        }

        return $this;
    }

    public function removeDietType(DietTypes $dietType): static
    {
        if ($this->dietTypes->removeElement($dietType)) {
            $dietType->removeRecipe($this);
        }

        return $this;
    }

    public function getImgFilename(): ?string
    {
        return $this->imgFilename;
    }

    public function setImgFilename(string $imgFilename): static
    {
        $this->imgFilename = $imgFilename;

        return $this;
    }

    public function isFree(): ?bool
    {
        return $this->free;
    }

    public function setFree(bool $free): static
    {
        $this->free = $free;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setRecipe($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getRecipe() === $this) {
                $comment->setRecipe(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\ManyToMany(targetEntity: Allergens::class, inversedBy: 'users')]
    private Collection $Allergens;

    #[ORM\ManyToMany(targetEntity: DietTypes::class, inversedBy: 'users')]
    private Collection $DietTypes;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $Firstname = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->Allergens = new ArrayCollection();
        $this->DietTypes = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Allergens>
     */
    public function getAllergens(): Collection
    {
        return $this->Allergens;
    }

    public function addAllergen(Allergens $allergen): static
    {
        if (!$this->Allergens->contains($allergen)) {
            $this->Allergens->add($allergen);
        }

        return $this;
    }

    public function removeAllergen(Allergens $allergen): static
    {
        $this->Allergens->removeElement($allergen);

        return $this;
    }

    /**
     * @return Collection<int, DietTypes>
     */
    public function getDietTypes(): Collection
    {
        return $this->DietTypes;
    }

    public function addDietType(DietTypes $dietType): static
    {
        if (!$this->DietTypes->contains($dietType)) {
            $this->DietTypes->add($dietType);
        }

        return $this;
    }

    public function removeDietType(DietTypes $dietType): static
    {
        $this->DietTypes->removeElement($dietType);

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): static
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function __toString()
    {
        return strval($this->id);
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/RecipesController.php
<?php

namespace App\Controller;

use App\Entity\Allergens;
use App\Entity\Comment;
use App\Entity\Recipe;
use App\Entity\User;
use App\Form\CommentType;
use App\Repository\AllergensRepository;
use App\Repository\CommentRepository;
use App\Repository\RecipeRepository;
use App\Repository\UserRepository;
use DateTime;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/recipes', name: 'recipes')]
class RecipesController extends AbstractController
{
    #[Route('/', name: 'recipes')]
    public function index(RecipeRepository $recipeRepository,
        ): Response
    {
        $recipesPay = $recipeRepository->findBy(array('free' => false));
        $recipesFree = $recipeRepository->findBy(array('free' => true));

        $user = $this->getUser();
        $allergensIds = [];
        if($user !== null){       

            if($allergensIds !== null){       
                foreach($user->getAllergens() as $allergens)
                {
                    array_push($allergensIds, $allergens->getId());
                }

            }
        }
        if ($allergensIds !== null) {
            $recipesConnect = $recipeRepository->findRecipesWithNoAllergens($allergensIds);
        }




        return $this->render('recipes/index.html.twig', [
            'controller_name' => 'RecipesController',
            'user' => $user,
            'recipesConnect' => $recipesConnect,
            'recipesPay' => $recipesPay,
            'recipesFree' => $recipesFree
        ]);
    }

    #[Route('/_recipe/{id}', name: '_recipe')]
    public function show(RecipeRepository $recipeRepository,
    Recipe $recipe,
    RecipeRepository $recipeRepo,
    CommentRepository $commentRepo,
    int $id=null,
    Request $request,
    EntityManagerInterface $entityManager,
    ): Response
    {
        $recipe = $recipeRepository->findBy(['id' => $id])[0];

        $user = $this->getUser();
        $allergensIds = [];
        $dietTypeIds = [];
        if($user !== null){       

            if($allergensIds !== null){       
                foreach($user->getAllergens() as $allergens)
                {
                    array_push($allergensIds, $allergens->getId());
                }
                foreach($user->getDietTypes() as $dietTypes)
                {
                    array_push($dietTypeIds, $dietTypes->getId());
                }

            }
        }
        if ($allergensIds !== null) {
            $recipesConnect = $recipeRepository->findRecipesWithNoAllergens($allergensIds);
            $recipesConnect2 = $recipeRepository->findRecipesWithNoDietTypes($dietTypeIds);

        }

        // Comment system
        $recipe = $recipeRepo->findBy(['id' => $id])[0];
        $date = new DateTime();
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);
        $comment = $form->getData();

        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
        }
        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $comment->setRecipe($recipe);
            $comment->setUser($user);
            $comment->setDate($date);
            
            $entityManager->persist($comment);
            $entityManager->flush();
            // do anything else you need here, like send an email

        }
        $comment = $commentRepo->findBy(array('recipe' => $recipe));
        foreach($comment as $comments) {
            $commentUser = $comments->getUser();
        }

        $formView = $form->createView();


        return $this->render('recipes/show.html.twig', [
            'controller_name' => 'RecipesController',
            'user' => $user,
            'recipesConnect' => $recipesConnect,
            'recipesConnect2' => $recipesConnect2,
            'recipes' => $recipe,
            'commentForm' => $form->createView(),
            'formView'=>$formView,
            'comments' => $comment,
            'commentUser' => $commentUser,

        ]);
    }

    public function showComment(
        CommentRepository $commentRepo,
        RecipeRepository $recipeRepo,
        int $id=null

        ) 
        {
            $recipe = $recipeRepo->findBy(['id' => $id])[0];
            $comment = $commentRepo->findBy(array('recipe_id' => $recipe));

            return $this->render('recipes/show.html.twig', [
                'controller_name' => 'RecipesController',
                'comments' => $comment
            ]);
    }
}

templates/recipes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecipesController!{% endblock %}

{% block body %}
{% if app.user %}
    {% for allergen in user.Allergens %}
            <li>{{ allergen.name|e }}</li>
    {% endfor %}
{% endif %}

<style>
    
</style>

<div class="container-fluid">
    {% if app.user %}
        <div class="row">
            <div class="col-lg-12 mt-4">
                <h1 class="page-header">Vos recettes</h1>
        </div>
            {% for recipes in recipesPay %}  
                    <div id="main" class="col mx-auto text-center main">
                            <h2>{{ recipes.name }}</h2>            
                                <div class="gallery_product d-inline col-lg-4 col-md-6 col-12 align-baseline">
                                    <a href="#" class="d-block mb-4">
                                        <img src={{ asset('uploads/imgFilename/' ~ recipes.imgFilename) }} alt="recipe" id="img-profil" class="img-fluid img-thumbnail active">
                                    </a>
                                </div>    
                                <div class="d-inline align-text-top">
                                    <h5>Description</h5>
                                    <p>{{ recipes.description }}</p>
                                    <li class="nav-item {{ app.request.get('_route') == '_recipe' }}">
                                        <a class="nav-link" href="{{ path('_recipe', {'id': recipes.id}) }}">Voir plus</a>
                                    </li>   
                                </div>
                    </div>
            {% endfor %}
    {% endif %}
        <div class="row">
            <div class="col-lg-12 mt-4">
                <h1 class="page-header">Nos recettes gratuites</h1>
            </div>
        </div>
            {% for recipes in recipesFree %}  
                    <div id="main" class="col mx-auto text-center main">
                            <h2>{{ recipes.name }}</h2>            
                                <div class="gallery_product d-inline col-lg-4 col-md-6 col-12 align-baseline">
                                    <a href="#" class="d-block mb-4">
                                        <img src={{ asset('uploads/imgFilename/' ~ recipes.imgFilename) }} alt="recipe" id="img-profil" class="img-fluid img-thumbnail active">
                                    </a>
                                </div>    
                                <div class="d-inline align-text-top">
                                    <h5>Description</h5>
                                    <p>{{ recipes.description }}</p>
                                    <li class="nav-item {{ app.request.get('_route') == '_recipe' }}">
                                        <a class="nav-link" href="{{ path('_recipe', {'id': recipes.id}) }}">Voir plus</a>
                                    </li>   
                                </div>
                    </div>
            {% endfor %}
    </div>

{% endblock %}

templates/recipes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe{% endblock %}

{% block body %}

<style>
    
</style>

<div class="container-fluid">
    {% if app.user %}
            <div id="main" class="col-lg-10 col-sm-11 mx-auto text-center main">
                <h2>{{ recipes.name }}</h2>            
                    <div class="gallery_product d-inline col-lg-4 col-md-6 col-12 align-baseline">
                        <a href="#" class="d-block mb-4">
                            <img src={{ asset('uploads/imgFilename/' ~ recipes.imgFilename) }} alt="recipe" id="img-profil" class="img-fluid img-thumbnail active">
                        </a>
                    </div>    
                    <div class="d-inline align-text-top">
                        <h5>Description</h5>
                        <p>{{ recipes.description }}</p>
                        <h5>Temps de préparation</h5>
                        <p>{ { recipes.preparationTime }}</p>
                        <h5>Temps de repos</h5>
                        <p>{{ recipes.break }}</p>
                        <h5>Temps de cuisson</h5>
                        <p>{{ recipes.cookingTime }}</p>
                        <h5>Liste des ingrédients</h5>
                        <p>{{ recipes.ingredients }}</p>
                        <h5>Les étapes à suivre</h5>
                        <p>{{ recipes.steps }}</p>   
                        <div class="col-lg-12">
                            <h2 class="mt-30">Commentaires</h2>
                            {% for comment in comments %}  
                                <div id="comment" class="col-10 mx-auto my-4 text-left comment">
                                    <p>{{ commentUser.firstname }} {{ commentUser.lastname }}</p>  
                                    <p>{{ comment.date|date('Y-m-d H:i:s')}}</p> 
                                    <p>{{ comment.comment }}</p>
                                </div>
                            {% endfor %}
  
                        </div>
                    </div>
                    <div id="main" class="col-lg-8 col-sm-11 mx-auto text-center main">
                        {{ form_errors(commentForm) }}

                        {{ form_start(commentForm) }}
                            {{ form_row(commentForm.comment) }}

                            <button type="submit" class="btn">Envoyer</button>
                        {{ form_end(commentForm) }}
                    </div>
            </div>
    {% endif %}

</div>

{% endblock %}